In [1]:
import numpy as np

创建数组

In [2]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.array[
    [1,2,3,4],
    [5,6,7,8],
]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [5]:
np.array[
    [1,2,3,4],
    [5,6,7,8]
]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [6]:
np.array([
    [1,2,3,4],
    [5,6,7,8],
])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
np.zeros(3,2
    )

TypeError: data type not understood

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((3,3
        ))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.zeros((4,3,3
        ))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
np.ones((2,3,4
        ))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

其他创建方式

In [12]:
np.arange()

TypeError: arange() missing required argument 'start' (pos 1)

In [13]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [15]:
np.linspace(1,5,8)

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [16]:
np.linspace(0,8,5)

array([0., 2., 4., 6., 8.])

In [17]:
np.logspace(0,2,4
           )

array([  1.        ,   4.64158883,  21.5443469 , 100.        ])

In [18]:
#使用base设置底数
np.logspace(0,5,4,base=2)

array([ 1.       ,  3.1748021, 10.0793684, 32.       ])

In [19]:
#使用random创建随机数
np.random.random((2,3))

array([[0.86411852, 0.60712332, 0.16085942],
       [0.82616287, 0.59201439, 0.43772257]])

In [22]:
np.random.randint(1,9,size=(3,3))

array([[1, 6, 3],
       [7, 8, 6],
       [2, 6, 3]])

In [24]:
#randn是一种产生标准正态分布的随机数或矩阵的函数
np.random.randn(3,3)

array([[ 0.66820833,  1.6250685 , -0.76140036],
       [-0.21505693,  1.25052468,  0.19418173],
       [ 2.38546993,  2.11969064, -0.06944712]])

In [30]:
#生成0-1之间的随机数
np.random.rand(9)

array([0.83353911, 0.83717542, 0.69132121, 0.91081301, 0.18653467,
       0.23454241, 0.10576441, 0.13167665, 0.42857828])