In [3]:
import numpy as np

In [9]:
#ndim 数组轴（维度）的个数，轴的个数被称作秩
arr = np.random.randint(1,9,size = (4,4))
print(arr)

[[6 7 5 7]
 [6 2 4 3]
 [6 2 1 5]
 [8 1 1 1]]


In [10]:
arr.ndim


2

In [11]:
arr.shape


(4, 4)

In [12]:
#用来描述数组中元素类型的对象
arr.dtype

dtype('int32')

In [14]:
arr.itemsize

4

In [15]:
arr.size


16

In [18]:
arr2 = arr.astype(float)
print(arr2)
print(arr2.dtype)

[[6. 7. 5. 7.]
 [6. 2. 4. 3.]
 [6. 2. 1. 5.]
 [8. 1. 1. 1.]]
float64


In [4]:
np.array(['python','c'])

array(['python', 'c'], dtype='<U6')

In [18]:
 #shape修改数组 ,-1是指根据数组元素数量自动计算该轴的长度值
arr3 = np.random.randint(1,9,(3,4))
print(arr3)
arr3.shape=(4,3)
print(arr3)
arr3.shape=(2,-1)

[[3 6 2 7]
 [6 7 7 8]
 [3 4 4 8]]
[[3 6 2]
 [7 6 7]
 [7 8 3]
 [4 4 8]]


In [21]:
#reshape修改
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [29]:
arr2 = arr.reshape(2,4)
arr2[0][3] = 100
arr2

array([[  0,   1,   2, 100],
       [  4,   5,   6,   7]])

arr

In [30]:
print(arr)

[  0   1   2 100   4   5   6   7]


In [49]:
arr = np.arange(15).reshape(3,-1,order = 'A')
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
#shape和reshape的区别
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.shape[0])
print(a.shape[1])
print(a.shape[2])

[[1 2 3 4]
 [5 6 7 8]]
2
4


IndexError: tuple index out of range

In [42]:
help(np.shape)

Help on function shape in module numpy:

shape(a)
    Return the shape of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.
    
    See Also
    --------
    alen
    ndarray.shape : Equivalent array method.
    
    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 2]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()
    
    >>> a = np.array([(1, 2), (3, 4)], dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (2,)
    >>> a.shape
    (2,)



In [43]:
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c