In [1]:
import numpy as np

# 数组与标量的运算

In [5]:
arr1 = np.random.randint(1,4,(3,3))
print(arr1)

[[3 1 3]
 [3 3 2]
 [3 3 1]]


In [6]:
print(arr1+2)

[[5 3 5]
 [5 5 4]
 [5 5 3]]


In [7]:
print(arr1/2)

[[1.5 0.5 1.5]
 [1.5 1.5 1. ]
 [1.5 1.5 0.5]]


In [9]:
arr2 = np.random.randint(1,4,(3,3))
print(arr2)

[[3 1 2]
 [3 3 1]
 [3 3 2]]


In [10]:
print(arr1/arr2)

[[1.  1.  1.5]
 [1.  1.  2. ]
 [1.  1.  0.5]]


In [11]:
print(arr1*arr2)

[[9 1 6]
 [9 9 2]
 [9 9 2]]


In [13]:
print(arr1-arr2)

[[ 0  0  1]
 [ 0  0  1]
 [ 0  0 -1]]


In [14]:
print(np.dot(arr1,arr2))

[[21 15 13]
 [24 18 13]
 [21 15 11]]


In [17]:
arr3 = np.random.randint(1,5,(3,2))
arr4 = np.random.randint(1,5,(2,4))
print(arr3)
print(arr4)

[[2 4]
 [1 3]
 [3 3]]
[[2 1 4 1]
 [1 1 3 2]]


In [18]:
print(np.dot(arr3,arr4))

[[ 8  6 20 10]
 [ 5  4 13  7]
 [ 9  6 21  9]]


# 索引和切片

In [24]:
arr = np.random.randint(1,5,(2,3,4))
print(arr)

[[[1 4 3 1]
  [4 2 4 4]
  [4 1 4 4]]

 [[3 2 3 2]
  [4 2 2 1]
  [2 2 4 1]]]


In [33]:
print(arr[0,0,1])

4
[[[1 4 3 1]
  [4 2 4 4]
  [4 1 4 4]]]


In [26]:
print(arr[:,:,1])

[[4 2 1]
 [2 2 2]]


In [27]:
print(arr[1,:,1])

[2 2 2]


In [28]:
print(arr[:,:,1:3:2])

[[[4]
  [2]
  [1]]

 [[2]
  [2]
  [2]]]


# 花式索引

In [34]:
arr = np.random.randint(1,9,(8,4))
arr

array([[5, 6, 4, 3],
       [6, 3, 2, 3],
       [1, 7, 3, 5],
       [3, 2, 2, 1],
       [3, 4, 4, 2],
       [5, 5, 1, 2],
       [8, 2, 1, 5],
       [8, 2, 1, 2]])

In [35]:
#取0 ，3， 5行数据
print(arr[[0,3,5]])

[[5 6 4 3]
 [3 2 2 1]
 [5 5 1 2]]


In [36]:
#取00,31,52的数据
print(arr[[0,3,5],[0,1,2]])

[5 2 1]


In [41]:
#希望取整行数据，如0行的0，3，1数据，3行的0，3，1数据，5行的0，3，1数据，使用索引器获取
print(arr[np.ix_([0,3,5],[0,3,1])])

[[5 3 6]
 [3 1 2]
 [5 2 5]]


# 布尔索引类型

In [42]:
arr = np.random.random((3,5))
print(arr)

[[0.21030725 0.19240901 0.40995925 0.20900922 0.27536266]
 [0.25352411 0.7466909  0.24908378 0.96841603 0.53636055]
 [0.46174334 0.70100225 0.70464069 0.46888059 0.96711023]]


In [47]:
arr2 = arr<0.5
arr2

array([[ True,  True,  True,  True,  True],
       [ True, False,  True, False, False],
       [ True, False, False,  True, False]])

In [59]:
name = np.array(['joe','tom','jake'])
score = np.array([
    [70,80,90],
    [78,98,87],
    [88,72,94],]
)
classes = np.array(['语文','数学','英语'])

In [61]:
name2 = name=='joe'
print(name2)
A = score[name=='joe']
B = score[name=='joe'].reshape((-1,))
print(A)
print(B)
print('tom的数学成绩为：',score[name=='tom'].reshape((-1,))[classes=='数学'])

[ True False False]
[[70 80 90]]
[70 80 90]
tom的数学成绩为： [98]
