In [1]:
import numpy as np

# 一元函数

In [15]:
arr = [[-5,3,8],[9,0,2]]
print(arr)
arr2 = np.exp(arr)
arr2

[[-5, 3, 8], [9, 0, 2]]


array([[6.73794700e-03, 2.00855369e+01, 2.98095799e+03],
       [8.10308393e+03, 1.00000000e+00, 7.38905610e+00]])

In [16]:
np.sign(arr)

array([[-1,  1,  1],
       [ 1,  0,  1]])

In [18]:
np.ceil(arr2)

array([[1.000e+00, 2.100e+01, 2.981e+03],
       [8.104e+03, 1.000e+00, 8.000e+00]])

In [19]:
np.floor(arr2)

array([[0.000e+00, 2.000e+01, 2.980e+03],
       [8.103e+03, 1.000e+00, 7.000e+00]])

In [20]:
np.rint(arr2)

array([[0.000e+00, 2.000e+01, 2.981e+03],
       [8.103e+03, 1.000e+00, 7.000e+00]])

In [21]:
np.modf(arr2)

(array([[0.00673795, 0.08553692, 0.95798704],
        [0.08392758, 0.        , 0.3890561 ]]),
 array([[0.000e+00, 2.000e+01, 2.980e+03],
        [8.103e+03, 1.000e+00, 7.000e+00]]))

In [22]:
np.isnan(arr2
        )

array([[False, False, False],
       [False, False, False]])

In [23]:
np.isfinite(arr2
           )

array([[ True,  True,  True],
       [ True,  True,  True]])

In [24]:
np.isinf(arr2)

array([[False, False, False],
       [False, False, False]])

In [25]:
np.cos(arr)

array([[ 0.28366219, -0.9899925 , -0.14550003],
       [-0.91113026,  1.        , -0.41614684]])